version: '3.8'
services:

  nginx:
    image: nginx:alpine
    container_name: lab8_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: .
    container_name: lab8_php
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab8_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
